#!/bin/bash

# Fighter Assembly generator
# Created by xiaoqzye@qq.com
# 2020/03/29

if [ $# -ne 2 ] ; then
	echo "Error, invalid number of arguments: $#" 1>&2
	exit 1
fi

if [ ! -f "$1" ] ; then
	echo "Error, file not found: $1" 1>&2
	exit 2
fi

echo -e "\n\n\t.globl $2"
echo -e "\t.hidden $2"
echo -e "\t.section .rodata"
echo -e "\t.balign 4"
echo    "$2:"
echo -e "\t.incbin \"$1\"\n"
exit 0

